apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-plus
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.30"
  virtualServerPort: 80
  virtualServerName: "nginx-plus"
  mode: standard
  snat: auto   
  pool:
    service: nginx-plus
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 10