apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  name: nginx-oss
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  virtualServerAddress: "10.1.10.20"
  virtualServerPort: 80
  virtualServerName: "nginx-oss"
  mode: standard
  snat: auto   
  pool:
    service: nginx-oss
    servicePort: 80
    monitor:
      type: tcp
      interval: 10
      timeout: 10